# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'savus' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for savus
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'

  target 'savusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'savusUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
